### ISSUE TITLE
Load Waypoints From External File

### ISSUE THREAD

**Issue by es-markjbyrne** [ShadowTraffic/requests#3]
Would it be possible to add support for loading waypoint coordinates for the waypoints generator from a csv file similar to how you allow external datasets to be loaded for the geolocation generator.  I would like to be able to generate long pre-determined journeys and it would be nice if I could do this without bloating the generator config.

Apologies if this is already possible and I have missed it in the docs.

**Comment by MichaelDrogalis** [comment]
Hey @es-markjbyrne, this is a great idea. What would you think about a new function that can load arbitrary JSON and inline it? Something like:

```json
{
            "_gen": "waypoints",
            "waypoints": {
                "_gen": "loadJsonFile",
                "file": "/foo/bar.json"
            },
            "speed": 500,
            "scale": 1,
            "unit": "degrees"
        }
```

It could be similar to `env`, which is also a sort of pre-processor. https://docs.shadowtraffic.io/functions/env/

**Comment by MichaelDrogalis** [comment]
I went ahead and added this one. :) https://docs.shadowtraffic.io/functions/loadJsonFile/

Let me know if you have any questions.
